# Analytics Rules build and deploy pipeline
# This pipeline publishes the rules file as an artifact and then uses a powershell task to deploy

# name: build and deploy Alert Rules
# resources:
#  pipelines:
#    - pipeline: Scripts
#      source: 'scriptsCI'
trigger: none
#  paths:
#    include:
#      - AnalyticsRules/*

stages:
- stage: build_alert_rules

  jobs:
    - job: AgentJob
      pool: Default
      #  name: Azure Pipelines
      #  vmImage: 'vs2017-win2016'
      steps:
       - task: CopyFiles@2
         displayName: 'Copy Alert Rules'
         inputs:
          SourceFolder: AnalyticsRules
          TargetFolder: '$(Pipeline.Workspace)'
      #  - task: Files-Validator@1
      #    inputs:
      #      rootDir: '$(Pipeline.Workspace)/*.json'
      #      validateXML: false
      #      validateJSON: true
      #      validateYAML: false
      #      validatePS: false
       - task: PublishPipelineArtifact@1
         displayName: 'Publish Pipeline Artifact'
         inputs:
          targetPath: Scripts
          artifact: Scripts
       - task: PublishPipelineArtifact@1
         displayName: 'Publish Artifact: RulesFile'
         inputs:
          targetPath: AnalyticsRules
          artifact: RulesFile
          

- stage: deploy_alert_rules
  jobs:
    - job: AgentJob
      pool: Default
      #  name: Azure Pipelines
      #  vmImage: 'windows-2019'
      variables: 
      - group: SentinelVariableGroup
      steps:
      #- task: DownloadPipelineArtifact@2
      #  inputs:
      #    buildType: 'current'
      #    targetPath: '$(Pipeline.Workspace)'
      - download: none
        artifact: RulesFile
        patterns: '*.json'
      - download: none
        artifact: Scripts
        patterns: '*.ps1'
      - task: AzurePowerShell@5
        displayName: 'Create and Update Alert Rules'
        inputs:
         azureSubscription: 'AzureRMManualSPNSentinel'
         ScriptPath: '$(Pipeline.Workspace)/Scripts/CreateAnalyticsRules.ps1'
         ScriptArguments: '-Workspace testSentinel -RulesFile analytics-rules.json'
         azurePowerShellVersion: LatestVersion
         pwsh: true